### ISSUE TITLE
Add Dark Mode 

### ISSUE THREAD

**Issue by niteshkmdev** [Nktech-Official/TicTacToe#1]
This is beginner Friendly Issue Add  Dark Mode To the Game .

**Comment by Muhammad-Shahid-Jamal** [comment]
hi i want to contribute to it can you assign it to me

**Comment by niteshkmdev** [comment]
_Start Working_ You May First Add Screen Shot in these Issue Before creating PR Or Add Screen Shot's In the PR

**Comment by Muhammad-Shahid-Jamal** [comment]
Light Mode
<img width="1679" alt="Screenshot 2023-10-03 at 3 43 10 PM" src="https://github.com/Nktech-Official/TicTacToe/assets/26340344/8bbaf235-1cec-4320-bd13-e6c83d23f198">
Dark Mode
<img width="1680" alt="Screenshot 2023-10-03 at 3 43 28 PM" src="https://github.com/Nktech-Official/TicTacToe/assets/26340344/93b78eb6-5363-448b-85a3-09c7cf671a05">

I have also added toggle animation to the theme toggle button.
let me know can i create a PR for this issue.
